/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projek;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//Class DATA
class Data {

    private int nik;
    private String keperluan;

    public Data(int nik, String keperluan) {
        this.nik = nik;
        this.keperluan = keperluan;
    }

    public int getKey() {
        return nik;
    }

    public String getkeperluan() {
        return keperluan;
    }
}

//CLASS HashTable
class HashTable {

    private Projek.Data[] hashArray;
    private int size;

    public HashTable(int size) {
        this.size = size;
        hashArray = new Projek.Data[size];
    }

    public int hashFunc(int key) {
        return key % size;
    }

    public void insert(int nik, String keperluan) {
        Projek.Data item = new Projek.Data(nik, keperluan);
        int key = item.getKey();
        int hashVal = hashFunc(key);
        while (hashArray[hashVal] != null) {
            ++hashVal;
            hashVal %= size;
        }
        hashArray[hashVal] = item;
    }

//    public String displayTable() {
//        for (int j = 0; j < size; j++) {
//            if (hashArray[j] != null) {
//                System.out.println(" | " + j + "\t | " + hashArray[j].getkeperluan() + " | ");
//            } else {
//                System.out.println(" | " + j + "\t | -- |");
//            }
//        }
//        return null;
//    }
//    public Projek.Data delete(int key) {
//        int hashVal = hashFunc(key);
//        while (hashArray[hashVal] != null) {
//            if (hashArray[hashVal].getKey() == key) {
//                Projek.Data temp = hashArray[hashVal];
//                hashArray[hashVal] = null;
//                return temp;
//            }
//            ++hashVal;
//            hashVal %= size;
//        }
//        return null;
//    }
    public Projek.Data find(int key) {
        int hashVal = hashFunc(key);
        while (hashArray[hashVal] != null) {
            if (hashArray[hashVal].getKey() == key) {
                return hashArray[hashVal];
            }
            ++hashVal;
            hashVal %= size;
        }
        return null;
    }

//    public Projek.Data getAll(int i) {
//        return hashArray[i];
//    }
    public String getkeperluan(int key) {
        int hashVal = hashFunc(key);
        while (hashArray != null) {
            if (hashArray[hashVal].getKey() == key) {
                return hashArray[hashVal].getkeperluan();
            }
        }
        return null;
    }
}

/**
 *
 * @author ASUS
 */
public class QApp extends javax.swing.JFrame {

    /**
     * Creates new form tes
     */
    public QApp() {
        initComponents();

    }

    int maxsize = 15;
    HashTable ht = new HashTable(maxsize);

    public static String getString() throws IOException {
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        String s = br.readLine();
        return s;
    }

    public static char getChar() throws IOException {
        String s = getString();
        return s.charAt(0);
    }

    public static int getInt() throws IOException {
        String s = getString();
        return Integer.parseInt(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JPanel();
        Loginpage = new javax.swing.JPanel();
        tuser = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        btlogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Homepage = new javax.swing.JPanel();
        btuser = new javax.swing.JButton();
        btteller = new javax.swing.JButton();
        total2 = new javax.swing.JLabel();
        tabout = new javax.swing.JButton();
        tout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Userpage = new javax.swing.JPanel();
        tkeperluan = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tnik = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        tno = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        bthapus = new javax.swing.JButton();
        tback2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbkeperluan = new javax.swing.JComboBox<>();
        Tellerpage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        home = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();
        bthapus2 = new javax.swing.JButton();
        btcall2 = new javax.swing.JButton();
        btclose2 = new javax.swing.JButton();
        loket2 = new javax.swing.JLabel();
        loket1 = new javax.swing.JLabel();
        btcall1 = new javax.swing.JButton();
        btclose1 = new javax.swing.JButton();
        jnamaantri = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Aboutpage = new javax.swing.JPanel();
        tback = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Office App");
        getContentPane().setLayout(new java.awt.CardLayout());

        frame.setPreferredSize(new java.awt.Dimension(1020, 700));
        frame.setLayout(new java.awt.CardLayout());

        Loginpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tuser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tuser.setBorder(null);
        Loginpage.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 360, 34));

        tpass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tpass.setBorder(null);
        Loginpage.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 350, 40));

        btlogin.setBorder(null);
        btlogin.setContentAreaFilled(false);
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        Loginpage.add(btlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 170, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LoginPage2.jpg"))); // NOI18N
        Loginpage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frame.add(Loginpage, "card5");

        Homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btuser.setBorder(null);
        btuser.setContentAreaFilled(false);
        btuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btuserActionPerformed(evt);
            }
        });
        Homepage.add(btuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 223, 500, 70));

        btteller.setBorder(null);
        btteller.setContentAreaFilled(false);
        btteller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttellerActionPerformed(evt);
            }
        });
        Homepage.add(btteller, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 389, 510, 70));

        total2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 160)); // NOI18N
        total2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homepage.add(total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 290, 330));

        tabout.setBorder(null);
        tabout.setContentAreaFilled(false);
        tabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taboutActionPerformed(evt);
            }
        });
        Homepage.add(tabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 510, 70));

        tout.setBorder(null);
        tout.setContentAreaFilled(false);
        tout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toutActionPerformed(evt);
            }
        });
        Homepage.add(tout, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 90, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HomePage.jpg"))); // NOI18N
        Homepage.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frame.add(Homepage, "card4");

        Userpage.setMinimumSize(new java.awt.Dimension(1020, 700));
        Userpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tkeperluan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tkeperluan.setBorder(null);
        Userpage.add(tkeperluan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 360, 40));

        tnama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tnama.setBorder(null);
        Userpage.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 240, 360, 40));

        tnik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tnik.setBorder(null);
        Userpage.add(tnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 330, 360, 40));

        talamat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        talamat.setBorder(null);
        Userpage.add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 420, 350, 45));

        tno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tno.setBorder(null);
        Userpage.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 510, 350, 45));

        btAdd.setBorder(null);
        btAdd.setContentAreaFilled(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        Userpage.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 150, 49));

        table.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No. ANTRIAN", "NAMA"
            }
        ));
        jScrollPane2.setViewportView(table);

        Userpage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 470, 100));

        total.setBackground(new java.awt.Color(229, 202, 202));
        total.setFont(new java.awt.Font("Segoe UI Semibold", 0, 90)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Userpage.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 450, 130));

        bthapus.setBorder(null);
        bthapus.setContentAreaFilled(false);
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        Userpage.add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 120, 50));

        tback2.setBorder(null);
        tback2.setContentAreaFilled(false);
        tback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tback2ActionPerformed(evt);
            }
        });
        Userpage.add(tback2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 80, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UserPage2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1020, 700));
        Userpage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cbkeperluan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== KEPERLUAN ==", "PERTEMUAN", "PERIZINAN", "PERJANJIAN" }));
        Userpage.add(cbkeperluan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 390, 70));

        frame.add(Userpage, "card4");

        Tellerpage.setMinimumSize(new java.awt.Dimension(1020, 700));
        Tellerpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No. ANTRIAN", "NAMA"
            }
        ));
        jScrollPane3.setViewportView(table2);

        Tellerpage.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 180, -1, 110));

        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        Tellerpage.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 59, 80, 70));

        tcari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tcari.setBorder(null);
        Tellerpage.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 270, 40));

        btcari.setBorder(null);
        btcari.setContentAreaFilled(false);
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        Tellerpage.add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 100, 40));

        bthapus2.setToolTipText("");
        bthapus2.setBorder(null);
        bthapus2.setContentAreaFilled(false);
        bthapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapus2ActionPerformed(evt);
            }
        });
        Tellerpage.add(bthapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 430, 46));

        btcall2.setBorder(null);
        btcall2.setContentAreaFilled(false);
        btcall2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcall2ActionPerformed(evt);
            }
        });
        Tellerpage.add(btcall2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 80, 60));

        btclose2.setBorder(null);
        btclose2.setContentAreaFilled(false);
        btclose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclose2ActionPerformed(evt);
            }
        });
        Tellerpage.add(btclose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 80, 50));

        loket2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 69)); // NOI18N
        loket2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loket2.setPreferredSize(new java.awt.Dimension(50, 10));
        Tellerpage.add(loket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 260, 130));

        loket1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 69)); // NOI18N
        loket1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loket1.setPreferredSize(new java.awt.Dimension(50, 20));
        Tellerpage.add(loket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 270, 130));

        btcall1.setBorder(null);
        btcall1.setContentAreaFilled(false);
        btcall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcall1ActionPerformed(evt);
            }
        });
        Tellerpage.add(btcall1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 80, 50));

        btclose1.setBorder(null);
        btclose1.setContentAreaFilled(false);
        btclose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclose1ActionPerformed(evt);
            }
        });
        Tellerpage.add(btclose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 80, 60));

        jnamaantri.setFont(new java.awt.Font("Segoe UI Semibold", 0, 69)); // NOI18N
        jnamaantri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tellerpage.add(jnamaantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 420, 130));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Tellerpage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AdminPage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1020, 700));
        Tellerpage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(386, 285));

        jLabel4.setText("Loket 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        Tellerpage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 399, 390, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(386, 285));

        jLabel6.setText("Loket 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 334, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        Tellerpage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 399, -1, -1));

        frame.add(Tellerpage, "card3");

        Aboutpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tback.setContentAreaFilled(false);
        tback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbackActionPerformed(evt);
            }
        });
        Aboutpage.add(tback, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 70, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AboutPage.jpg"))); // NOI18N
        Aboutpage.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frame.add(Aboutpage, "card7");

        getContentPane().add(frame, "card5");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int noAntri = 0;
    int head = -1;
    int tail = -1;
    int size = 10;
    int kapasitas;
    int x = 0;
    String tempdata;
    int tempnomor;
    String data[] = new String[size];
    int nomor[] = new int[size];

//    String keperluan[] = new String [size]; 

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        if (tnama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "MOHON ISI NAMA ANDA", "Infomration", JOptionPane.INFORMATION_MESSAGE);
        } else if (tail == size - 1) {
            JOptionPane.showMessageDialog(null, "MOHON MAAF ANTRIAN PENUH", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else if (tnik.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "MOHON ISI NIK ANDA ", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else if (tno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "MOHON ISI NOMOR TELEPON ANDA", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else if (tkeperluan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "MOHON ISI KEPERLUAN ANDA", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else if (tail == -1) {
            head++;
            noAntri++;
            nomor[head] = noAntri;
            data[head] = tnama.getText();
            tail++;
            JOptionPane.showMessageDialog(null, "NOMOR ANTRIAN ANDA " + nomor[head], "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            tail++;
            noAntri++;
            nomor[tail] = noAntri;
            data[tail] = tnama.getText();
            JOptionPane.showMessageDialog(null, "NOMOR ANTRIAN ANDA " + nomor[tail], "Information", JOptionPane.INFORMATION_MESSAGE);
            tnama.setText("");
        }
        table.setModel(new DefaultTableModel(null, new String[]{"No. Antrian", "Nama"}));
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int a = 0; a <= tail; a++) {
            model.addRow(new Object[]{nomor[a], data[a]});
            table.setModel(model);
            tnama.setText("");
        }

        int NIK = Integer.parseInt(tnik.getText());
        ht.insert(NIK, tkeperluan.getText());

        tno.setText("");
        tkeperluan.setText("");
        tnik.setText("");
        tno.setText("");
        talamat.setText("");
        total.setText("" + (tail + 1));
        total2.setText("" + (tail + 1));
//        if (tnama.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "MOHON LENGKAPI NAMA ANDA",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else if (tnik.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "MOHON LENGKAPI NIK ANDA",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else if (talamat.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "MOHON LENGKAPI ALAMAT ANDA",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else if (tno.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "MOHON LENGKAPI NOMOR ANDA",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else if (tno.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "MOHON LENGKAPI KEPERLUAN ANDA",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else if (tail == -1) {
//            head++;
//            noAntri++;
//            nomor[head] = noAntri;
//            data[head] = tnama.getText();
//            tail++;
//            JOptionPane.showMessageDialog(null, "NOMOR ANTRIAN ANDA " + nomor[head],
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//            tnama.setText("");
//            tnik.setText("");
//        } else if (tail == size - 1) {
//            JOptionPane.showMessageDialog(null, "MOHON MAAF ANTRIAN PENUH",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            tail++;
//            noAntri++;
//            nomor[tail] = noAntri;
//            data[tail] = tnama.getText();
//            JOptionPane.showMessageDialog(null, "NOMOR ANTRIAN ANDA " + nomor[tail],
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//            tnama.setText("");
//            tnik.setText("");
//        }
//        table.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
//        DefaultTableModel model = (DefaultTableModel) table.getModel();
//        for (int a = 0; a <= tail; a++) {
//            model.addRow(new Object[]{nomor[a], data[a]});
//            table.setModel(model);
//            tnama.setText("");
//            tnik.setText("");
//            tno.setText("");
//            talamat.setText("");
//            tkeperluan.setText("");
////            cbkeperluan.setSelectedItem("== KEPERLUAN ==");
//        }
//        total.setText("" + (tail + 1));
//        total2.setText("" + (tail + 1));
//        int NIK = Integer.parseInt(tnik.getText());
//        String KEPERLUAN = tkeperluan.getText();
//        ht.insert(NIK, KEPERLUAN);
//        int nik = Integer.valueOf(tnik.getText());
//        String KEPERLUAN = tkeperluan.getText();
//        ht.insert(nik, KEPERLUAN);

    }//GEN-LAST:event_btAddActionPerformed

    private void btuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btuserActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) frame.getLayout();
        card.show(frame, "page User");
        Tellerpage.setVisible(false);
        Userpage.setVisible(true);
        Homepage.setVisible(false);

        table.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
        for (int o = 0; o <= tail; o++) {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.addRow(new Object[]{nomor[o], data[o]});
            table.setModel(model);
        }
        total.setText("" + (tail + 1));
        total2.setText("" + (tail + 1));
    }//GEN-LAST:event_btuserActionPerformed

    private void bttellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttellerActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) frame.getLayout();
        card.show(frame, "page Teller");
        Tellerpage.setVisible(true);
        Userpage.setVisible(false);
        Homepage.setVisible(false);

        table2.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
        for (int n = 0; n <= tail; n++) {
            DefaultTableModel model = (DefaultTableModel) table2.getModel();
            model.addRow(new Object[]{nomor[n], data[n]});
            table2.setModel(model);
        }
    }//GEN-LAST:event_bttellerActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        // TODO add your handling code here:
        String user = "Izzul";
        String pass = "Izzul123";
        String user2 = "admin";
        String pass2 = "admin123";

        if (user.equalsIgnoreCase(tuser.getText()) && pass.equalsIgnoreCase(tpass.getText())) {
            CardLayout card = (CardLayout) frame.getLayout();
            card.show(frame, "page User");
            Loginpage.setVisible(false);
            Homepage.setVisible(true);
        } else if (user2.equalsIgnoreCase(tuser.getText()) && pass2.equalsIgnoreCase(tpass.getText())) {
            CardLayout card = (CardLayout) frame.getLayout();
            card.show(frame, "page Teller");
            Tellerpage.setVisible(true);
            Loginpage.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Lengkapi Data dengan benar!");
            tuser.setText("");
            tpass.setText("");
            btlogin.requestFocus();
        }
    }//GEN-LAST:event_btloginActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
//        if (tail == -1) {
//            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            tempdata = data[head];
//            tempnomor = nomor[head];
//            for (int i = 0; i < tail; i++) {
//                data[i] = data[i + 1];
//                nomor[i] = nomor[i + 1];
//            }
//            tail--;
//            JOptionPane.showMessageDialog(null, "No Antrian " + tempnomor + " " + tempdata + " TELAH DIHAPUS DARI ANTRIAN",
//                    "Information", JOptionPane.INFORMATION_MESSAGE);
//        }
//        table2.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
//        for (int c = 0; c <= tail; c++) {
//            DefaultTableModel model = (DefaultTableModel) table2.getModel();
//
//            model.addRow(new Object[]{nomor[c], data[c]});
//            table2.setModel(model);
//            table.setModel(model);
//            total.setText("" + (tail));
//            total2.setText("" + (tail));
//        }
//COBA-COBA
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        if (row >= 0) {
            int ok = JOptionPane.showConfirmDialog(null, "Data Akan Dihapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                model.removeRow(x);
            }
        }
        total.setText("" + (tail));
        total2.setText("" + (tail));
        //coba
//        table2.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
//        for (int p = 0; p <= tail; p++) {
//            DefaultTableModel model1 = (DefaultTableModel) table2.getModel();
//            model1.removeRow(x);
//            table2.setModel(model1);
//        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
//        int NIK = Integer.parseInt(tnik.getText());
//        int nik = Integer.valueOf(tnik.getText());
//        String KEPERLUAN = tkeperluan.getText();
//        ht.insert(nik, KEPERLUAN);
        int CARI = Integer.parseInt(tcari.getText());
        if (ht.find(CARI) != null) {
            JOptionPane.showMessageDialog(null, "Nomor NIK " + CARI + "\n" + "Keperluan: " + ht.getkeperluan(CARI), "Information", JOptionPane.INFORMATION_MESSAGE);
            CardLayout card = (CardLayout) frame.getLayout();
            card.show(frame, "page Teller");
            Loginpage.setVisible(true);
            Tellerpage.setVisible(false);
        } else if (ht.find(CARI) == null) {
            JOptionPane.showMessageDialog(null, "Nomor NIK tidak tersedia", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

//        int CARI = Integer.parseInt(tcari.getText());
//        if (ht.find(CARI) != null) {
//            JOptionPane.showMessageDialog(null, "Nomor NIK " + CARI + "\n" + "Keperluan: " + ht.getkeperluan(CARI), "Information", JOptionPane.INFORMATION_MESSAGE);
//        } else if (ht.find(CARI) == null) {
//            JOptionPane.showMessageDialog(null, "Nomor NIK tidak tersedia", "Information", JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_btcariActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) frame.getLayout();
        card.show(frame, "page User");
        Tellerpage.setVisible(false);
        Homepage.setVisible(true);

        total.setText("" + (tail + 1));
        total2.setText("" + (tail + 1));
    }//GEN-LAST:event_homeActionPerformed

    private void toutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toutActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Anda akan Log Out?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            CardLayout card = (CardLayout) frame.getLayout();
            card.show(frame, "page User");
            Loginpage.setVisible(true);
            Homepage.setVisible(false);
            tuser.setText("");
            tpass.setText("");
        }
    }//GEN-LAST:event_toutActionPerformed

    private void tbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbackActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) frame.getLayout();
        card.show(frame, "page User");
        Aboutpage.setVisible(false);
        Homepage.setVisible(true);
    }//GEN-LAST:event_tbackActionPerformed

    private void taboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taboutActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) frame.getLayout();
        card.show(frame, "page User");
        Aboutpage.setVisible(true);
        Homepage.setVisible(false);
    }//GEN-LAST:event_taboutActionPerformed

    private void tback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tback2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) frame.getLayout();
        card.show(frame, "page User");
        Userpage.setVisible(false);
        Homepage.setVisible(true);

//            total2.setText("" + (tail + 1));

    }//GEN-LAST:event_tback2ActionPerformed

    private void btcall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcall1ActionPerformed
        // TODO add your handling code here:
        if (tail == -1) {
            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            loket1.setText("");
            jnamaantri.setText("KOSONG");
        } else {
            loket1.setText("" + nomor[0]);
            tempdata = data[head];
            tempnomor = nomor[head];
            for (int i = 0; i < tail; i++) {
                data[i] = data[i + 1];
                nomor[i] = nomor[i + 1];
            }
            tail--;
            //COBA
            jnamaantri.setText("" + (nomor[head]));
        }

        table2.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
        for (int k = 0; k <= tail; k++) {
            DefaultTableModel model = (DefaultTableModel) table2.getModel();

            model.addRow(new Object[]{nomor[k], data[k]});
            table2.setModel(model);
        }

    }//GEN-LAST:event_btcall1ActionPerformed

    private void btcall2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcall2ActionPerformed
        // TODO add your handling code here:
        if (tail == -1) {
            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            loket2.setText("KOSONG");
            jnamaantri.setText("KOSONG");
        } else {
            loket2.setText("" + nomor[0]);
            tempdata = data[head];
            tempnomor = nomor[head];
            for (int i = 0; i < tail; i++) {
                data[i] = data[i + 1];
                nomor[i] = nomor[i + 1];
            }
            tail--;
            jnamaantri.setText("" + (nomor[head]));
        }

        table2.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
        for (int l = 0; l <= tail; l++) {
            DefaultTableModel model = (DefaultTableModel) table2.getModel();

            model.addRow(new Object[]{nomor[l], data[l]});
            table2.setModel(model);
        }
    }//GEN-LAST:event_btcall2ActionPerformed

    private void bthapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapus2ActionPerformed
        // TODO add your handling code here:
        if (tail == -1) {
            JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            tempdata = data[head];
            tempnomor = nomor[head];
            for (int i = 0; i < tail; i++) {
                data[i] = data[i + 1];
                nomor[i] = nomor[i + 1];
            }
            tail--;
            JOptionPane.showMessageDialog(null, "No Antrian " + tempnomor + " " + tempdata + " TELAH DIHAPUS DARI ANTRIAN",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        table2.setModel(new DefaultTableModel(null, new String[]{"No. ANTRIAN", "NAMA"}));
        for (int c = 0; c <= tail; c++) {
            DefaultTableModel model = (DefaultTableModel) table2.getModel();

            model.addRow(new Object[]{nomor[c], data[c]});
            table2.setModel(model);
        }
    }//GEN-LAST:event_bthapus2ActionPerformed

    private void btclose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclose1ActionPerformed
        // TODO add your handling code here:
        loket1.setText("X");
    }//GEN-LAST:event_btclose1ActionPerformed

    private void btclose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclose2ActionPerformed
        // TODO add your handling code here:
        loket2.setText("X");
    }//GEN-LAST:event_btclose2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nik = "200605110001";
        String keperluan = "Jadwal Perjanjian";
        String nik2 = "200605110170";
        String keperluan2 = "Peminjaman Gedung";

        if (nik.equalsIgnoreCase(tcari.getText())) {
            JOptionPane.showMessageDialog(null, "Nomor NIK " + nik + "\n" + "Keperluan: " + keperluan, "Information", JOptionPane.INFORMATION_MESSAGE);
            tcari.setText("");
        } else if (nik2.equalsIgnoreCase(tcari.getText())) {
            JOptionPane.showMessageDialog(null, "Nomor NIK " + nik2 + "\n" + "Keperluan: " + keperluan2, "Information", JOptionPane.INFORMATION_MESSAGE);
            tcari.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Nomor NIK " + tcari.getText() + " Tidak Tersedia", "Information", JOptionPane.INFORMATION_MESSAGE);
            tcari.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aboutpage;
    private javax.swing.JPanel Homepage;
    private javax.swing.JPanel Loginpage;
    private javax.swing.JPanel Tellerpage;
    private javax.swing.JPanel Userpage;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btcall1;
    private javax.swing.JButton btcall2;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btclose1;
    private javax.swing.JButton btclose2;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bthapus2;
    private javax.swing.JButton btlogin;
    private javax.swing.JButton btteller;
    private javax.swing.JButton btuser;
    private javax.swing.JComboBox<String> cbkeperluan;
    private javax.swing.JPanel frame;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jnamaantri;
    private javax.swing.JLabel loket1;
    private javax.swing.JLabel loket2;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JButton tabout;
    private javax.swing.JTextField talamat;
    private javax.swing.JButton tback;
    private javax.swing.JButton tback2;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tkeperluan;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnik;
    private javax.swing.JTextField tno;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total2;
    private javax.swing.JButton tout;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
